baseURL: 'https://huydq.dev/'
title: HuyDQ's Blog
paginate: 10
theme: PaperMod
defaultContentLanguage: vi

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
disableKinds: ['section']

googleAnalytics: G-5KF148C0X6

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: HuyDQ's Blog
  description: 'Learning - Coding - Writing - Spamming.'
  keywords: [blog, dev, programming, web, mobile]
  images: ['/icons/cat-thumbnail.png']
  DateFormat: '02/01/2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: '/icons/favicon.png'
    favicon16x16: '/icons/favicon16.png'
    favicon32x32: '/icons/favicon32.png'
    apple_touch_icon: '/icons/favicon.png'
    safari_pinned_tab: '/icons/favicon.png'

  label:
    text: 'huydq.dev'

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    Title: ''
    Content: ''

  socialIcons:
    - name: facebook
      url: 'https://www.facebook.com/huydq.dev'
    - name: github
      url: 'https://github.com/robinhuy'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/5229299/robin-huy'

  analytics:
    google:
      SiteVerificationTag: 'G-5KF148C0X6'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

markup:
  highlight:
    lineNos: true
    style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: slides
      name: Slides
      url: /slides/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50
